export { indexOf, slice } from "./array"
export { dedent } from "./dedent"
export { err } from "./err"
export { humanSize, humanDuration } from "./human"
export { jsonLines } from "./jsonLines"
export { clamp } from "./math"
export { basename } from "./path"
export { parseHTML } from "./parseHTML"
export { template, parseVars } from "./template"
