export { indexOf, slice } from "./array"
export { err } from "./err"
export { dedent, fmtCount, fmtSize, fmtDuration, fmtDate, humanize } from "./fmt"
export { jsonLines } from "./jsonLines"
export { basename } from "./path"
export { template, parseVars } from "./template"
