CREATE TABLE Chat (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
) STRICT;

CREATE TABLE ChatMessage (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  chat_id INTEGER NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  FOREIGN KEY (chat_id) REFERENCES Chat(id)
) STRICT;